select * from eliminados;
select * from isbn;
select * from idiomas;
select * from estados;
select * from multas;
select * from areas;
select * from paises;
select * from metodos;
select * from categorias;
select * from autores;
select * from editoriales;
select * from distribuidores;
select * from libros;
select * from trabajadores;
select * from clientes;
select * from correoTrabajadores;
select * from correoClientes;
select * from direccionTrabajadores;
select * from direccionClientes;
select * from telefonoTrabajadores;
select * from telefonoClientes;
select * from arriendos;
select * from facturas;
select * from boletas;
select * from compras;
select * from ventas;
select * from nub1;
select * from nub2;
select * from nub3;


drop table nub3;
drop table nub2;
drop table nub1;
drop table ventas;
drop table compras;
drop table boletas;
drop table facturas;
drop table arriendos;
drop table telefonoClientes;
drop table telefonoTrabajadores;
drop table direccionClientes;
drop table direccionTrabajadores;
drop table correoClientes;
drop table correoTrabajadores;
drop table clientes;
drop table trabajadores;
drop table libros;
drop table distribuidores;
drop table editoriales;
drop table autores;
drop table categorias;
drop table metodos;
drop table paises;
drop table areas;
drop table multas;
drop table estados;
drop table idiomas;
drop table isbn;
drop table eliminados;